# Generated by Django 4.1 on 2022-10-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='body',
            new_name='comment',
        ),
    ]
