# Generated by Django 4.1 on 2022-10-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_body_postcomment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='post_connected',
        ),
    ]
